# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 860e3ebd0bbff6bbc7c344f31b7785209c5cdc2f5fc6c5413073c236803cd9e726454be3480523ce5e312bdbb0e3eb1d3bbca82ad1899c1eb080927807457f9a

test:
  secret_key_base: e91708d56878f2e74533e3cb6f26e59f2a02e6b75572e99de86bd7197b0ef3ea7340ff19fbf336a6ec2a144c518ba179fe04892ab67e6544e4afd9e3d768d552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
